name: video_player_header
description: Flutter plugin for displaying inline video with other Flutter
  widgets on Android and iOS. And Add Header .
author: Flutter Team <flutter-dev@googlegroups.com>
version: 0.10.2+3
homepage: https://github.com/sanrixue/videoPlayerWithHeader.git

flutter:
  plugin:
    androidPackage: io.flutter.plugins.videoplayer
    iosPrefix: FLT
    pluginClass: VideoPlayerPlugin

dependencies:
  meta: "^1.0.5"
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=1.5.0 <2.0.0"
